"""Cross-validate C# parser output against intelhex ground truth.

Runs the C# parser via 'dotnet run' and compares results against
the ground-truth JSON fixtures generated by intelhex.
"""

import json
import subprocess
import sys
from pathlib import Path

BLAZOR_CLI = Path("blazor/HexFlex.Cli")
FIXTURES_DIR = Path("test_output/fixtures")
TEST_FILES_DIR = Path("test_files")


def run_csharp(command: list[str]) -> dict:
    """Run the C# CLI and parse JSON output."""
    result = subprocess.run(
        ["dotnet", "run", "--project", str(BLAZOR_CLI), "--"] + command,
        capture_output=True, text=True, timeout=120
    )
    if result.returncode != 0:
        print(f"  ERROR: dotnet run failed:\n{result.stderr}", file=sys.stderr)
        sys.exit(1)
    return json.loads(result.stdout)


def compare_values(label: str, expected, actual, failures: list):
    """Compare two values and record any mismatch."""
    if expected != actual:
        failures.append(f"  {label}: expected {expected}, got {actual}")


def main():
    print("=== Cross-Validation: C# Parser vs intelhex Ground Truth ===\n")
    all_failures = []

    # --- Validate each test file ---
    for hex_file in sorted(TEST_FILES_DIR.glob("*.hex")):
        fixture_file = FIXTURES_DIR / f"{hex_file.stem}_ground_truth.json"
        print(f"--- {hex_file.name} ---")

        with open(fixture_file) as f:
            gt = json.load(f)

        print(f"  Running C# parser...")
        cs = run_csharp(["parse", str(hex_file)])

        failures = []
        compare_values("total_data_bytes", gt["total_data_bytes"], cs["total_data_bytes"], failures)
        compare_values("min_address", gt["min_address"], cs["min_address"], failures)
        compare_values("max_address", gt["max_address"], cs["max_address"], failures)
        compare_values("segment_count", gt["segment_count"], cs["segment_count"], failures)

        # Compare each segment
        for i, (gt_seg, cs_seg) in enumerate(zip(gt["segments"], cs["segments"])):
            compare_values(f"segment[{i}].start", gt_seg["start"], cs_seg["start"], failures)
            compare_values(f"segment[{i}].end", gt_seg["end"], cs_seg["end"], failures)
            compare_values(f"segment[{i}].size", gt_seg["size"], cs_seg["size"], failures)

        if failures:
            print(f"  FAILED ({len(failures)} mismatches):")
            for f in failures:
                print(f)
            all_failures.extend(failures)
        else:
            print(f"  PASSED: {cs['total_data_bytes']:,} bytes, {cs['segment_count']} segments")
        print()

    # --- Validate comparison ---
    hex_files = sorted(TEST_FILES_DIR.glob("*.hex"))
    if len(hex_files) == 2:
        print(f"--- Comparison: {hex_files[0].name} vs {hex_files[1].name} ---")

        with open(FIXTURES_DIR / "comparison_ground_truth.json") as f:
            gt = json.load(f)

        print(f"  Running C# comparer...")
        cs = run_csharp(["compare", str(hex_files[0]), str(hex_files[1])])

        failures = []
        compare_values("total_addresses", gt["total_addresses"], cs["total_addresses"], failures)
        compare_values("unchanged", gt["unchanged"], cs["unchanged"], failures)
        compare_values("modified", gt["modified"], cs["modified"], failures)
        compare_values("added", gt["added"], cs["added"], failures)
        compare_values("removed", gt["removed"], cs["removed"], failures)

        if failures:
            print(f"  FAILED ({len(failures)} mismatches):")
            for f in failures:
                print(f)
            all_failures.extend(failures)
        else:
            print(f"  PASSED: {cs['modified']:,} modified, {cs['added']:,} added, {cs['removed']:,} removed, {cs['unchanged']:,} unchanged")
        print()

    # --- Summary ---
    if all_failures:
        print(f"\nFAILED: {len(all_failures)} total mismatches")
        sys.exit(1)
    else:
        print("ALL CROSS-VALIDATION CHECKS PASSED")


if __name__ == "__main__":
    main()
